# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 843515defa191a5090c928a5962b02d6f4f1579924c20865d760a3b49ddb2000095288d1ffbd8fd020ce4cb51a04210c2df30d1034036aa1ce06eace522c0295

test:
  secret_key_base: 7d20e50b8617f5b48632a6683ae069409918df3734ecbf2886f7c9c3a48e5990c357ac0c8361e47887a4843d4fd56221581fb5782a13c2d8092d49d95b1afd5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
